// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_Final__Libreria_.Data;

#nullable disable

namespace Proyecto_Final__Libreria_.Migrations
{
    [DbContext(typeof(DBconexion))]
    partial class DBconexionModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyecto_Final__Libreria_.Models.Calificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Nota")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.ToTable("Calificaciones");
                });

            modelBuilder.Entity("Proyecto_Final__Libreria_.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Proyecto_Final__Libreria_.Models.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Cantidad")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<decimal?>("Total")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("id_Producto")
                        .HasColumnType("int");

                    b.Property<int?>("id_UsuarioRol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("id_Producto");

                    b.HasIndex("id_UsuarioRol");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("Proyecto_Final__Libreria_.Models.Descuento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int?>("Porcentaje")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Descuentos");
                });

            modelBuilder.Entity("Proyecto_Final__Libreria_.Models.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Cantidad")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("Subtotal")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("id_Descuento")
                        .HasColumnType("int");

                    b.Property<int?>("id_Producto")
                        .HasColumnType("int");

                    b.Property<int?>("id_Promocion")
                        .HasColumnType("int");

                    b.Property<int?>("id_Venta")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("id_Descuento");

                    b.HasIndex("id_Producto");

                    b.HasIndex("id_Promocion");

                    b.HasIndex("id_Venta");

                    b.ToTable("DetalleVentas");
                });

            modelBuilder.Entity("Proyecto_Final__Libreria_.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Cantidad")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Precio")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("id_Categoria")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("id_Categoria");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Proyecto_Final__Libreria_.Models.Promocion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("Promociones");
                });

            modelBuilder.Entity("Proyecto_Final__Libreria_.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Proyecto_Final__Libreria_.Models.Usuario_Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("id_Rol")
                        .HasColumnType("int");

                    b.Property<int?>("id_Usuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("id_Rol");

                    b.HasIndex("id_Usuario");

                    b.ToTable("Usuario_Roles");
                });

            modelBuilder.Entity("Proyecto_Final__Libreria_.Models.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CI")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("Usuarioss");
                });

            modelBuilder.Entity("Proyecto_Final__Libreria_.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("Fecha")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Total")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("id_Calificacion")
                        .HasColumnType("int");

                    b.Property<int?>("id_Usuario")
                        .HasColumnType("int");

                    b.Property<int?>("id_UsuarioRol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("id_Calificacion");

                    b.HasIndex("id_Usuario");

                    b.HasIndex("id_UsuarioRol");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("Proyecto_Final__Libreria_.Models.Compra", b =>
                {
                    b.HasOne("Proyecto_Final__Libreria_.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("id_Producto");

                    b.HasOne("Proyecto_Final__Libreria_.Models.Usuario_Rol", "UsuarioRol")
                        .WithMany()
                        .HasForeignKey("id_UsuarioRol");

                    b.Navigation("Producto");

                    b.Navigation("UsuarioRol");
                });

            modelBuilder.Entity("Proyecto_Final__Libreria_.Models.DetalleVenta", b =>
                {
                    b.HasOne("Proyecto_Final__Libreria_.Models.Descuento", "Descuento")
                        .WithMany()
                        .HasForeignKey("id_Descuento");

                    b.HasOne("Proyecto_Final__Libreria_.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("id_Producto");

                    b.HasOne("Proyecto_Final__Libreria_.Models.Promocion", "Promocion")
                        .WithMany()
                        .HasForeignKey("id_Promocion");

                    b.HasOne("Proyecto_Final__Libreria_.Models.Venta", "Venta")
                        .WithMany()
                        .HasForeignKey("id_Venta");

                    b.Navigation("Descuento");

                    b.Navigation("Producto");

                    b.Navigation("Promocion");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Proyecto_Final__Libreria_.Models.Producto", b =>
                {
                    b.HasOne("Proyecto_Final__Libreria_.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("id_Categoria");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Proyecto_Final__Libreria_.Models.Usuario_Rol", b =>
                {
                    b.HasOne("Proyecto_Final__Libreria_.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("id_Rol");

                    b.HasOne("Proyecto_Final__Libreria_.Models.Usuarios", "Usuarios")
                        .WithMany()
                        .HasForeignKey("id_Usuario");

                    b.Navigation("Rol");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Proyecto_Final__Libreria_.Models.Venta", b =>
                {
                    b.HasOne("Proyecto_Final__Libreria_.Models.Calificacion", "Calificacion")
                        .WithMany()
                        .HasForeignKey("id_Calificacion");

                    b.HasOne("Proyecto_Final__Libreria_.Models.Usuarios", "Usuarios")
                        .WithMany()
                        .HasForeignKey("id_Usuario");

                    b.HasOne("Proyecto_Final__Libreria_.Models.Usuario_Rol", "Usuario_Rol")
                        .WithMany()
                        .HasForeignKey("id_UsuarioRol");

                    b.Navigation("Calificacion");

                    b.Navigation("Usuario_Rol");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
